version: '3'
services:
  user-service:
    image: user-service:0.0.1
    ports:
    - "80:80"
  database:
    image: mssql-server-linux:latest
    ports:
    - "1433:1433"
    environment:
    - "SA_PASSWORD=Pass@word"
    - "ACCEPT_EULA=Y"

